---
title: "Backlog"
description: |
  Ter idéia do que postar é fácil, difícil mesmo é desenvolver tudo isso na mesma velocidade! Nesta seção eu reuno tudo aquilo que eu já tive de ideia de escrever sobre, mas que faltou tempo para tornar realidade. Pretendo manter visibilidade disso aqui para me ajudar a não me esquecer e, quem sabe, receber algum feedback para priorizar um deles!
theme: theme.css
---

# Web Scrapping
- Como raspar os anúncios do ZapImóveis;
- Interagindo com a API REST da Ludopedia;
- Interagindo com a API XML da BoardGameGeek.

# TidyTuesday
### Y2021W36 - BirdBaths 
O dataset da semana contém uma lista de espécies de pássaros que foram avistados em _bird baths_ na Austrália por cidadões-cientistas entre os anos 2014 e 2015, em áreas urbanas e rurais e algumas bioregiões da Austrália. Gostaria de:  
  
- De que forma variam os padrões de biodiversidade da assembléia de pássaros entre áreas urbanas e rurais dentro e entre bioregiões?   
- Podemos prever em que bioregião estamos a partir da lista de espécies de pássaros?  

### Y2021W52 - Starbucks drinks
O dataset da semana trata das características de vários drinks e cafés produzidos pelo Starbucks. Seria interessante ver qual a relação entre esses drinks em uma dimensão multivariada - talvez um embedding ou also assim.

# Análises

- A descrição do apartamento está associada ao seu preço?  
- Quantos tipos diferentes de jogos de tabuleiro existem?  
- Que fatores estão associados ao sucesso de um jogo de tabuleiro?  
- Podemos prever se um jogo de tabuleiro lançado no Brasil será um big hit?  
- Como gerar recomendações de um jogo a partir de suas características?  
- [On going] Quais as regras de associação existentes entre as cartas dos decks de Gwent?  
- Qual o deck de Gwent mais fácil de montar a partir do baralho que eu tenho?  
- Cartas de facções diferentes formam grupos distintos com base nas informações de texto do `tooltip`?  
- Como visualizar a relação entre as cartas de Gwent?  
- Que carta devo adicionar ao meu deck de Gwent para complementar o que tenho com estas outras _n_ cartas?  
- A que facção pertence uma carta de acordo com a sua ilustração?
- Como gerar nos cartas de Gwent a partir das já existentes?

# Testando Pacotes

- Testando o pacote `modeltime` para modelar séries temporais;  
- Testando o ecossistema do pacote `fpp3` para modelar séries temporais;  
- [On going] Testando o pacote `arules` para modelar regras de associação.  
