---
title: "F1 Acidentes"
description: |
  A short description of the post.
author:
  - first_name: Nicholas 
    last_name: Marino
    url: https://github.com/nacmarino
date: 09-06-2021
categories:
  - tidytuesday
  - tidymodels
output:
  distill::distill_article:
    self_contained: false
    toc: true
    code_folding: true
    highlight: rstudio
draft: true
---

```{r setup, include=FALSE}
# setando as opções gerais dos code chunks
knitr::opts_chunk$set(echo = FALSE, code_folding = FALSE, fig.align = 'center')

# presetando o ggplot2
library(ggplot2)

# setando o tema geral do ggplot2
theme_set(new = theme_minimal(base_family = 'IBM Plex Sans'))

# atualizando o tema
theme_update(
  plot.title    = element_text(face = 'bold', size = 10),
  plot.subtitle = element_text(size = 8),
  plot.caption  = element_text(size = 8),
  axis.title    = element_text(face = 'bold', size = 8),
  axis.text     = element_text(color = 'black', size = 8),
  strip.text    = element_text(face = 'bold', size = 8)
)
```

# Motivação

```{r}
# carregando os pacotes necessários
library(tidyverse) # core
# library(tidytuesdayR) # ler os arquivos do tidytuesday
library(fs) # manipular paths
library(lubridate) # trablhar com datas
library(readxl) # carregar dados de excel
library(skimr) # descricao do dataframe

# carregando os dados de dispositivos de segurança na F1
safety <- read_excel(path = 'data/f1_safety.xlsx', skip = 1)
# safety <- read_excel(path = '_posts/2021-09-11-f1-acidentes/data/f1_safety.xlsx', skip = 1)
```

blablabla

```{r carrega_dados}
# carregando todos os dados a partir do github do tidytuesday
# tt_dataset <- tt_load(x = 2021, week = 37) # se você quiser baixar os dados direto da fonte

# carregando a copia local dos dados
## extraindo os paths das copias locais
paths_copias_locais <- dir_ls(path = 'data/', regexp = '.rds')
# paths_copias_locais <- dir_ls(path = '_posts/2021-09-11-f1-acidentes/data/', regexp = '.rds')

## criando vetor de nomes dos arquivos
nomes_arquivos <- paths_copias_locais %>% 
  path_file() %>% 
  path_ext_remove()

## carregando os arquivos em uma lista
tt_dataset <- map(.x = paths_copias_locais, .f = read_rds)

## renomeando os elementos da lista
names(tt_dataset) <- nomes_arquivos
```

blablabla

```{r de_para_status}
## adicionando o dicionario de resultados
resultados <- left_join(x = tt_dataset$results,
                        y = tt_dataset$status,
                        by = 'statusId')
resultados
```

blablabla

```{r base_variavel_resposta}
## vetor com as categorias que vou usar como acidente
# categorias_acidente <- c('Accident', 'Collision', 'Spun off', 'Injured', 'Injury', 
#                          'Fatal accident', 'Eye injury', 'Collision damage', 'Damage')
categorias_acidente <- c('Accident', 'Collision', 'Injured', 'Injury', 'Fatal accident', 'Eye injury')

## juntando padrao de regex para os acidentes
regex_acidentes <- paste0(categorias_acidente, collapse = '|')

## mapeando os acidentes por prova
acidentes_por_prova <- resultados %>% 
  # selecionando as colunas de interesse
  select(raceId, driverId, constructorId, status) %>% 
  # agrupando pela prova, piloto e construtor
  group_by(raceId, driverId, constructorId) %>% 
  # juntando o status do piloto em cada prova em uma só string
  summarise(status = paste(status, collapse = ', '), .groups = 'drop') %>% 
  # codificando a ocorrencia de um acidente
  mutate(
    acidente = str_detect(string = status, pattern = regex_acidentes)
  ) %>% 
  # agrupando por prova
  group_by(raceId) %>% 
  # sumarizando a base
  summarise(
    # calculando a quantidade de acidentes por prova
    n_acidentes = sum(acidente),
    # criando flag para a ocorrencia de acidentes na prova
    tem_acidente = n_acidentes > 0
  )
acidentes_por_prova
```

# Preparação dos Dados

blablabla

```{r fe_dispositivos_de_seguranca}
## dispositivos de seguranca disponiveis ano a ano e total
dispositivos_seguranca <- safety %>%
  # expandindo a coluna de ano para conter todos os anos do inicio ao atual
  mutate(
    Year = map(.x = Year, .f = seq, to = year(Sys.Date()), by = 1)
  ) %>% 
  # desaninhando a list column
  unnest(cols = Year) %>% 
  # removendo o nome original da intevenção
  select(-Intervention) %>% 
  # passando a tabela para o formato largo
  pivot_wider(id_cols = Year, names_from = ID, values_from = ID, values_fn = length, values_fill = 0) %>% 
  group_by(Year) %>% 
  rowwise() %>% 
  mutate(
    n_safety = sum(c_across(I001:I025))
  )
dispositivos_seguranca
```

blablabla

```{r outras_features, code_folding = TRUE}
## quantidade de pilotos e construtores por prova
participantes_por_prova <- resultados %>% 
  # pegando os valores unicos das chaves primarias por prova
  distinct(raceId, driverId, constructorId) %>% 
  # agrupando por prova
  group_by(raceId) %>% 
  # quantidade de pilotos e construtores por prova
  summarise(
    n_pilotos      = n_distinct(driverId),
    n_construtores = n_distinct(constructorId)
  )

## calculando a quantidade de voltas em cada prova
voltas_por_prova <- resultados %>% 
  # considerando apenas os pilotos que concluiram cada prova
  filter(status == 'Finished') %>% 
  # selecionando as colunas de interesse
  select(raceId, laps) %>% 
  # pegando o valor maximo da quantidade de voltas por prova
  group_by(raceId) %>% 
  summarise(laps = max(laps))

## mapeando cada circuito à uma prova
provas <- left_join(x = tt_dataset$races,
                    y = tt_dataset$circuits,
                    by = 'circuitId') %>% 
  # removendo URL da wikipedia
  select(-contains('url'), -circuitRef, -circuitId, -round) %>%
  # renomeando o nome do GP e do circuito
  rename(gp = name.x, circuit = name.y) %>% 
  # levantando informacoes de data
  mutate(
    data     = paste(date, time),
    data     = as_datetime(data),
    mes      = month(data),
    semana   = isoweek(x = data),
    turno_pm = pm(data),
    decada   = (year %/% 10) * 10
  ) %>% 
  select(-date, -time)
```

```{r}
left_join(x = tt_dataset$driver_standings,
          y = select(tt_dataset$races, raceId, year, round),
          by = 'raceId') %>% 
  arrange(year, driverId, round) %>% 
  group_by(year, driverId) %>% 
  filter(year == 2008, driverId %in% c(1, 2)) %>% View()
```

blablabla

```{r junta_features_por_prova}
## juntando informacoes das provas com a quantidade de participantes e construtores
features_por_prova <- left_join(x = provas,
                             y = participantes_por_prova,
                             by = 'raceId') %>% 
  ## juntando de voltas por prova
  left_join(y = voltas_por_prova,
            by = 'raceId') %>% 
  # juntando informacoes dos dispositivos de seguranca disponiveis por ano
  left_join(y = dispositivos_seguranca, by = c('year' = 'Year')) %>% 
  # substituindo os valores NA por 0
  mutate(
    across(I001:n_safety, replace_na, 0)
  )
features_por_prova
```

blablabla

```{r cria_base_analitica}
df <- left_join(x = acidentes_por_prova, y = features_por_prova, by = 'raceId')
df
```

# Análise Exploratória

blablabla

```{r skim_da_base_analitica, layout = 'l-body-outset'}
skim(data = df)
```

blablabla

```{r target_por_decada, layout = 'l-body-outset', dpi = 200, fig.height=4, fig.width=8}
df %>% 
  # agrupando por decada
  group_by(decada) %>% 
  # calculando a proporcao de provas com acidente
  summarise(
    proporcao = mean(tem_acidente), 
    .groups = 'drop'
  ) %>% 
  # reordenando a coluna de decada para o fill
  mutate(
    decada_fill = fct_reorder(.f = as.factor(decada),
                              .x = proporcao, .desc = TRUE)
  ) %>% 
  # criando a figura
  ggplot(mapping = aes(x = decada, y = proporcao, fill = decada_fill)) +
  geom_col(color = 'black') +
  scale_x_continuous(breaks = seq(from = 1950, to = 2020, by = 10)) +
  scale_y_continuous(breaks = seq(from = 0, to = 1, by = 0.2), limits = c(0, 1)) +
  scale_fill_brewer(type = 'div', palette = 'RdBu') +
  labs(
    title    = 'Proporção de provas com acidente por década',
    subtitle = 'A frequência de acidentes foi muito alta entre as décadas de 70 e 80, mas voltou a cair logo na década de 90.',
    caption  = 'Quanto mais fria a cor do preenchimento, mais desejado é aquele comportamento para a variável analisada.',
    x        = 'Década',
    y        = 'Proporção de provas com acidente'
  ) +
  theme(legend.position = 'none')
```

blablabla

```{r seguranca_por_decada, layout = 'l-body-outset', dpi = 200, fig.height=4, fig.width=8}
# criando figura da quantidade de intervenções por decada
safety %>% 
  # convertendo os anos em decadas
  mutate(decada = (Year %/% 10) * 10) %>% 
  # contando quantidade de intervencoes de seguranca por decada
  count(decada, name = 'intervencoes') %>% 
  # adicionando linha para a decada de 2020 que esta faltando
  add_row(decada = 2020, intervencoes = 0) %>% 
  # reordenando a coluna de decada para o fill
  mutate(
    decada_fill = fct_reorder(.f = as.factor(decada),
                              .x = intervencoes, .desc = TRUE)
  ) %>% 
  # criando a figura
  ggplot(mapping = aes(x = decada, y = intervencoes, fill = decada_fill)) +
  geom_col(color = 'black') +
  scale_x_continuous(breaks = seq(from = 1950, to = 2020, by = 10)) +
  scale_fill_brewer(type = 'div', palette = 'RdBu', direction = -1) +
  labs(
    title    = 'Quantidade de intervenções relacionadas à segurança dos pilotos entre as décadas',
    subtitle = 'Houve um aumento na quantidade de intervenções relacionadas à segurança entre as décadas de 90 e o início dos anos 2000.',
    caption  = 'Quanto mais fria a cor do preenchimento, mais desejado é aquele comportamento para a variável analisada.',
    x        = 'Década',
    y        = 'Intervenções relacionadas à segurança'
  ) +
  theme(legend.position = 'none')
```

blablabla

```{r acidentes_por_circuito, layout = 'l-body-outset', dpi = 200, fig.height=8, fig.width = 9}
df %>% 
  # codificando circuitos infrequentes como classe a parte
  mutate(circuit = fct_lump_min(f = circuit, min = 4)) %>%
  # agrupando no circuito
  group_by(circuit) %>% 
  # calculando a proporcao de provas com acidente
  summarise(
    proporcao = mean(tem_acidente), 
    obs       = n(),
    .groups = 'drop'
  ) %>% 
  # reordenando os niveis do circuito
  mutate(
    circuit = fct_reorder(.f = circuit, .x = proporcao)
  ) %>% 
  # criando a figura
  ggplot(mapping = aes(x = proporcao, y = circuit, fill = proporcao)) +
  geom_col(color = 'black') +
  scale_x_continuous(breaks = seq(from = 0, to = 1, by = 0.2), limits = c(0, 1)) +
  scale_fill_distiller(type = 'div', palette = 'RdBu') +
  labs(
    title    = 'Proporção de acidentes por prova no registro histórico',
    subtitle = 'Existem registros de acidentes em todas as provas que ocorreram em alguns circuitos.',
    caption  = 'Quanto mais fria a cor do preenchimento, mais desejado é aquele comportamento para a variável analisada.',
    x        = 'Proporção de provas com acidente'
  ) +
  theme(
    legend.position = 'none',
    axis.title.y = element_blank()
  )
```

blablabla

```{r acidentes_por_mes, layout = 'l-body-outset', dpi = 200, fig.height = 5, fig.width = 5}
# criando a figura da propoção de provas com acidentes por mes
df %>% 
  # criando coluna com o mes por extenso em portugues
  mutate(mes_str = month(x = data, label = TRUE, locale = 'pt_BR', abbr = FALSE)) %>% 
  # agrupando pelo mes
  group_by(mes_str) %>% 
  # calculando a proporcao de provas com acidentes por mes
  summarise(proporcao = mean(tem_acidente)) %>% 
  # plotando a figura
  ggplot(mapping = aes(x = mes_str, y = proporcao, fill = proporcao)) +
  geom_col() +
  geom_text(mapping = aes(label = round(x = proporcao, digits = 2)), nudge_y = 0.06) +
  scale_fill_fermenter(type = 'div', palette = 'RdBu', direction = -1) +
  coord_polar() +
  labs(
    title = 'Proporção de provas com acidente por mês entre todos os anos no histórico',
    caption  = 'Quanto mais fria a cor do preenchimento, mais desejado é aquele comportamento para a variável analisada.'
    ) +
  theme(
    legend.position = 'none',
    axis.text.y     = element_blank(),
    axis.title      = element_blank()
    )
```

# Análise dos Dados

# Conclusão